export const REVIEW_TEST_SCHEMA = `
create table "user"(id text primary key);
create table portfolios(id serial primary key,user_id text references "user" on delete cascade,name text not null,description text,kind text default 'REAL',currency text default 'USD',is_default boolean default false,created_at timestamp default now(),review_timezone text,review_week_starts_on integer default 1);
create table trades(id serial primary key,portfolio_id integer not null references portfolios on delete cascade,user_id text not null references "user" on delete cascade,symbol text not null,side text not null,status text default 'OPEN',entry_date timestamp not null,exit_date timestamp,entry_price numeric,target_price numeric,exit_price numeric,quantity numeric,fees numeric default 0,net_pnl numeric,return_percent numeric,setup_id integer,mistake text,confidence text,notes text,screenshots jsonb default '[]',import_hash text unique,edit_revision integer default 0 not null,annotation_revision integer default 0 not null,reviewed_at timestamptz,reviewed_execution_fingerprint text);
create table cash_flows(id serial primary key,user_id text not null references "user" on delete cascade,portfolio_id integer not null references portfolios on delete cascade,occurred_at timestamp not null,amount numeric not null,kind text not null,note text,import_hash text,created_at timestamp default now());
create table review_periods(id serial primary key,user_id text not null references "user" on delete cascade,portfolio_id integer not null references portfolios on delete cascade,kind text not null,status text default 'DRAFT' not null,period_start date not null,period_end_exclusive date not null,timezone_snapshot text not null,week_starts_on_snapshot integer not null,currency_snapshot text not null,template_version integer default 1,intent text default '',execution text default '',lesson text default '',next_action text default '',notes text default '',commitment_reflection text default '',previous_review_id integer,previous_commitment_snapshot text,revision integer default 0,created_at timestamptz default now(),updated_at timestamptz default now(),completed_at timestamptz,result_snapshot jsonb,unique(portfolio_id,kind,period_start));
create table review_source_trades(review_id integer references review_periods on delete cascade,trade_id integer references trades on delete restrict,execution_fingerprint text not null,snapshot jsonb not null,included_in_snapshot boolean default false,linked_at timestamptz default now(),primary key(review_id,trade_id));
create table review_source_cash_flows(review_id integer references review_periods on delete cascade,cash_flow_id integer references cash_flows on delete restrict,execution_fingerprint text not null,snapshot jsonb not null,included_in_snapshot boolean default false,linked_at timestamptz default now(),primary key(review_id,cash_flow_id));
alter table trades add column initial_stop_price numeric, add column initial_target_price numeric, add column initial_risk_amount numeric, add column initial_risk_percent numeric, add column initial_risk_snapshot jsonb, add column management_stop_price numeric, add column risk_correction_history jsonb, add column exit_quote_to_account_rate numeric, add column pnl_calculation_snapshot jsonb;
`;
